### ISSUE TITLE
Find by instance in zcl_di_context

### ISSUE THREAD

**Issue by kidneybox** [swixfort/Sdw.Abap.Di#12]
**Issue**
`zcl_di_context->get` doesn't find an object if it's been added using `container->register_instance`.

Also you can use `cl_type_objectdescr` to combine the interface/class logic into one block.

**Suggestion**
`METHOD get.`
`  data object_descr type ref to cl_abap_objectdescr.`

`  object_descr ?= cl_abap_typedescr=>describe_by_name( i_class_name ).`

` loop . . .`

` if ( registry_entry->instance is bound `
`  and object_descr->applies_to( registry_entry->instance ) = abap_true ) `
`    or object_descr->applies_to_class( registry_entry->class_name ) = abap_true.`
` . . . `

Note: You could also change `zcl_di_container->get_instance` to pass in the `cl_abap_objectdescr` instead of `i_class_name`. Skipping the `if i_class_name = entry->class_name` check and always using `if i_type->applies_to(...) or i_type->applies_to_class(...)` can remove a code path and not hurt performance any noticeable amount.

**Comment by swixfort** [comment]
Hi @kidneybox thank you for opening the issue; I'll look into it and your suggestion!

**Comment by swixfort** [comment]
Hi @kidneybox 
sorry it took so long. Work was quite demanding.
I think the changes should suffice now. Will test a bit more before merging with master.
Maybe you may want to check it out in the develop branch.

Additionally I moved your note to #13  

Cheers

**Comment by kidneybox** [comment]
Thanks! I haven't tested, but it looks ok.

No problem, I've been pretty busy too. I'm still figuring out DI/IoC, so this has been a great base to learn with, but I haven't done anything major with it yet. 

I did throw in a stack to check for circular references. I'm working on figuring out how best to add something like Autofac's "PreserveExistingDefaults()" option. If I figure out how forking/git work, I'll try to share.
